language: python
python:
  - "3.6"
services:
  - mysql
env:
  - DJANGO=1.8 DB=mysql
install:
  - pip install -r requirements.txt
before_script:
  - python manage.py test migrate
script:
  - python manage.py test
