# Generated by Django 2.2.5 on 2019-10-17 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0002_prueba_aplicacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prueba',
            name='herramienta',
        ),
    ]
