# Generated by Django 2.2.5 on 2019-11-01 06:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0004_auto_20191016_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='tipo_ejecucion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='solicitudes.TipoEjecucion'),
        ),
    ]
