# Generated by Django 2.2.5 on 2019-11-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0005_auto_20191101_0115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_ejecucion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_ejecucion',
            field=models.ManyToManyField(to='solicitudes.TipoEjecucion'),
        ),
    ]
