# Generated by Django 2.2.5 on 2019-11-01 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solicitudes', '0006_auto_20191101_0122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solicitud',
            name='aplicacion',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='aplicacion',
            field=models.ManyToManyField(to='solicitudes.Aplicacion'),
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='herramienta',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='herramienta',
            field=models.ManyToManyField(to='solicitudes.Herramienta'),
        ),
        migrations.RemoveField(
            model_name='solicitud',
            name='tipo_prueba',
        ),
        migrations.AddField(
            model_name='solicitud',
            name='tipo_prueba',
            field=models.ManyToManyField(to='solicitudes.TipoPrueba'),
        ),
    ]
